# NumPy

## 📋 Table of Contents
1. [Understanding Arrays](#1-understanding-arrays-ndarray)
2. [Creating Special Arrays](#2-creating-special-arrays)
3. [Indexing & Slicing](#3-indexing-and-slicing)
4. [Array Operations (Mathematical & Indexing)](#4-array-operations-mathematical-and-indexing)
5. [Random Sampling & Normalizations](#5-random-sampling-and-normalization)
6. [Useful NumPy Functions](#6-useful-numpy-functions)
7. [Linear Algebra in NumPy](#7-linear-algebra-in-numpy)

## 1. Understanding Arrays (ndarray)
- NumPy arrays are more efficient than Python lists for numerical operations.
- Learn how to create arrays using:

In [2]:
import numpy as np

# Creating a 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1, '\n')

# Creating a 2D array (matrix)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2, '\n')

# Creating a 3D array
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr3, '\n')

[1 2 3 4 5] 

[[1 2 3]
 [4 5 6]] 

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] 



- Understand array shapes and dimensions (.shape, .ndim, .size).

<b>.shape</b> → Returns a tuple representing the number of elements along each axis. \
<b>.ndim</b> → Returns the number of dimensions (axes). \
<b>.size</b> → Returns the total number of elements in the array.


In [3]:
print(arr2.shape)   # (2, 3) → 2 rows, 3 columns
print(arr2.size)    # 6 → Total elements
print(arr2.ndim)    # 2 → Number of dimensions
print(arr2.dtype)   # int → Data type of elements

(2, 3)
6
2
int64


## 2. Creating Special Arrays

In [15]:
print(np.zeros((3, 3)), '\n')   # 3x3 matrix filled with 0s
print(np.ones((2, 4)),'\n')    # 2x4 matrix filled with 1s
print(np.full((3, 3), 9),'\n') # 3x3 matrix filled with 9s
print(np.eye(4),'\n')          # 4x4 identity matrix
print(np.random.rand(2, 3),'\n')  # 2x3 matrix with random values

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

[[9 9 9]
 [9 9 9]
 [9 9 9]] 

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 

[[0.93352448 0.79362093 0.00932645]
 [0.32696253 0.47562898 0.79989309]] 



## 3. Indexing and Slicing

In [11]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[1])    # 20
print(arr[-1])   # 50
print(arr[1:4])  # [20, 30, 40]

20
50
[20 30 40]


- Indexing in 2D Arrays

In [16]:
matrix = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(matrix[1, 2])   # 60 (row 1, col 2)
print(matrix[:, 1])   # [20, 50, 80] (all rows, col 1)
print(matrix[0, :])   # [10, 20, 30] (first row)

60
[20 50 80]
[10 20 30]


- Use Boolean indexing:

In [20]:
arr = np.array([1,2,3,4,5])
arr[arr > 2]  # Returns elements greater than 3

array([3, 4, 5])

## 4. Array Operations (Mathematical and Indexing)
- Basic operations (+, -, *, /) work element-wise.
- Learn indexing and slicing:

In [17]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(arr1 + arr2)  # [5, 7, 9]
print(arr1 - arr2)  # [-3, -3, -3]
print(arr1 * arr2)  # [4, 10, 18]
print(arr1 / arr2)  # [0.25, 0.4, 0.5]

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


- Element-wise and Broadcasting

In [21]:
arr = np.array([1, 2, 3])
print(arr * 2)  # [2, 4, 6]

[2 4 6]


## 5. Random Sampling and Normalization
- Generating random numbers for data simulation:

In [5]:
np.random.randn(10)  # 10 random numbers from a normal distribution

array([ 0.44111839,  2.05332413,  0.76888288, -0.52490855,  0.27063437,
        0.34251631, -0.09509985, -0.48788557,  0.3798861 , -0.41387553])

- Normalizing data (important for ML):

In [7]:
arr = (arr - np.mean(arr)) / np.std(arr)
arr

array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])

## 6. Useful NumPy Functions

- Aggregation Functions

In [22]:
arr = np.array([10, 20, 30, 40, 50])

print(arr.sum())    # 150
print(arr.mean())   # 30.0
print(arr.min())    # 10
print(arr.max())    # 50
print(arr.std())    # Standard deviation

150
30.0
10
50
14.142135623730951


- Reshaping Arrays

In [23]:
arr = np.array([1, 2, 3, 4, 5, 6])

reshaped = arr.reshape(2, 3)  # Convert to 2 rows, 3 columns
print(reshaped)

[[1 2 3]
 [4 5 6]]


- Stacking Arrays

In [24]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(np.vstack((arr1, arr2)))  # Vertical stack
print(np.hstack((arr1, arr2)))  # Horizontal stack

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


## 7. Linear Algebra in NumPy
<b>Linear algebra</b>

- Dot Product

In [25]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.dot(a, b))  # (1*4 + 2*5 + 3*6) = 32

32


- Matrix Multiplication

In [26]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(np.matmul(A, B))  # Matrix multiplication

[[19 22]
 [43 50]]


- Inverse of a Matrix

In [27]:
A = np.array([[1, 2], [3, 4]])
print(np.linalg.inv(A))  # Inverse of A

[[-2.   1. ]
 [ 1.5 -0.5]]


- Eigenvalues and Eigenvectors

In [28]:
A = np.array([[2, -1], [-1, 2]])
eigenvalues, eigenvectors = np.linalg.eig(A)

print(eigenvalues)   # Eigenvalues
print(eigenvectors)  # Eigenvectors

[3. 1.]
[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]
