# NumPy Beginner Exercises
### ========================

In [1]:
# 1. Import required libraries
import numpy as np

In [2]:
# 2. Exercise 1
# Display current numpy version
version = np.__version__ # Replace with your answer

In [22]:
# 3. Exercise 2
# Create a 1D numpy array of numbers from 0 to 9
arr_1d = np.arange(10)  # Replace with your answer
arr_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
# 4. Exercise 3
# Create a 3x3 boolean numpy array
bool_arr = np.ones((3,3), dtype=bool)  # Replace with your answer
bool_arr

# remember 1 is represented as True and 0 is represented as false 

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [18]:
# Question : Extract all odd numbers from array
# input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# output: array([1, 3, 5, 7, 9])

arr = np.arange(10)
odd_numbers =  arr[arr%2 == 1] # Replace with your answer
odd_numbers

array([1, 3, 5, 7, 9])

In [29]:
# 6. Exercise 5
# Replace all odd numbers in arr_1d with -1

arr = np.arange(10)
arr[arr%2 == 1] = -1  # Replace with your answer
arr_replaced = arr
arr_replaced

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [7]:
# 7. Exercise 6
# Replace all odd numbers with -1 without modifying the original array

arr = np.arange(10)
arr_copy = None  # Replace with your answer

In [8]:
# 8. Exercise 7
# Reshape an array of size 9 to 3x3
reshaped_arr = None  # Replace with your answer

In [9]:
# 9. Exercise 8
# Stack two arrays vertically
a = np.arange(6).reshape(2, 3)
b = np.arange(6, 12).reshape(2, 3)
v_stacked = None  # Replace with your answer

In [10]:
# 10. Exercise 9
# Stack two arrays horizontally
h_stacked = None  # Replace with your answer

In [12]:
# 11. Exercise 10
# Create a custom sequence: [1,2,3] repeated 3 times and then [1,2,3] tiled 3 times
rep = None  # Replace with your answer
tile = None  # Replace with your answer

In [13]:
# 12. Exercise 11
# Get common items between two arrays
a1 = np.array([1, 2, 3, 4, 5])
a2 = np.array([4, 5, 6, 7, 8])
common = None  # Replace with your answer

In [14]:
# 13. Exercise 12
# Remove elements of a1 that are in a2
diff = None  # Replace with your answer

In [15]:
# 14. Exercise 13
# Get the positions where elements of a1 and a2 match
match_positions = None  # Replace with your answer

In [16]:
# 15. Exercise 14
# Extract all numbers between 5 and 10 from the array
array_range = np.array([1, 4, 6, 9, 12, 15])
filtered = None  # Replace with your answer

In [17]:
# 16. Exercise 15
# Turn a scalar function into one that works on arrays
def scalar_func(x):
    return x ** 2 + 2 * x + 1

vectorized_func = None  # Replace with your answer
vectorized_result = None  # Apply vectorized_func to np.array([1, 2, 3])

# ---------------------------
# ✅ ASSERTIONS FOR MARKING
# ---------------------------

In [23]:
assert version == np.__version__
assert np.array_equal(arr_1d, np.arange(10))
assert bool_arr.shape == (3, 3) and bool_arr.dtype == bool
assert np.array_equal(odd_numbers, np.array([1, 3, 5, 7, 9]))
assert np.array_equal(arr_replaced[arr_replaced % 2 == 1], np.array([]))
assert np.array_equal(arr_copy, np.where(arr_1d % 2 == 1, -1, arr_1d))
assert reshaped_arr.shape == (3, 3)
assert np.array_equal(v_stacked, np.vstack((a, b)))
assert np.array_equal(h_stacked, np.hstack((a, b)))
assert np.array_equal(rep, np.repeat([1, 2, 3], 3))
assert np.array_equal(tile, np.tile([1, 2, 3], 3))
assert np.array_equal(common, np.intersect1d(a1, a2))
assert np.array_equal(diff, np.setdiff1d(a1, a2))
assert np.array_equal(match_positions, np.where(a1 == a2)[0])
assert np.array_equal(filtered, np.array([6, 9]))
assert callable(vectorized_func)
assert np.array_equal(vectorized_result, np.array([4, 9, 16]))

print("✅ All assertions passed! Well done.")

NameError: name 'arr_replaced' is not defined