# NumPy

## 1. Understanding Arrays (ndarray)
- NumPy arrays are more efficient than Python lists for numerical operations.
- Learn how to create arrays using:

In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

- Understand array shapes and dimensions (.shape, .ndim, .size).

<b>.shape</b> → Returns a tuple representing the number of elements along each axis. \
<b>.ndim</b> → Returns the number of dimensions (axes). \
<b>.size</b> → Returns the total number of elements in the array.


## 2. Array Operations (Mathematical & Indexing)
- Basic operations (+, -, *, /) work element-wise.
- Learn indexing and slicing:

In [3]:
arr[1:4]  # Slices elements from index 1 to 3

array([2, 3, 4])

- Use Boolean indexing:

In [4]:
arr[arr > 3]  # Returns elements greater than 3

array([4, 5])

## 4. Random Sampling & Normalization
- Generating random numbers for data simulation:

In [5]:
np.random.randn(10)  # 10 random numbers from a normal distribution

array([ 0.44111839,  2.05332413,  0.76888288, -0.52490855,  0.27063437,
        0.34251631, -0.09509985, -0.48788557,  0.3798861 , -0.41387553])

- Normalizing data (important for ML):

In [7]:
arr = (arr - np.mean(arr)) / np.std(arr)
arr

array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])